### ISSUE TITLE
strange artifacts using randr

### ISSUE THREAD

**Issue by brianclinkenbeard** [jonls/redshift#461]
When using the randr method there are somewhat noticeable flickering horizontal lines. They are especially noticeable while the color temperature is changing however this happens consistently. This does not occur using the vidmode method. I'm using redshift 1.11, mesa 17.0.4, and nouveau (xf86-video-nouveau 1.0.14). 

my `~/.config/redshift.conf`:
```[redshift]
location-provider=manual
brightness-day=1.0
brightness-night=0.8
adjustment-method=randr
```

There are no more than one instance of redshift running:
```
 ~ » pgrep redshift
2293
```

**Comment by maandree** [comment]
Sometimes, flats screens have problems with flickering dots and flickering lines (not necessarily horizontal or vertical), often, but not always, depending on the colour on those dots. This can often be fixed by unplugging the monitor plug it back in. Could this be the issue?

**Comment by jonls** [comment]
I'm closing this since there has been no more activity from the original poster.

**Comment by brianclinkenbeard** [comment]
@maandree @jonls unplugging the monitor did not seem to fix the issue. :confused: 

again, this also does not occur using the "vidmode" method, only when using `-m randr`.

**Comment by jonls** [comment]
This may be a driver issue then, since vidmode is working?

**Comment by brianclinkenbeard** [comment]
maybe a problem with the xorg nouveau driver? I had this problem on archlinux and have recently migrated to debian and the problem persists.
